##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/libcafemixer
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - gettext
    - git
    - gtk-doc-tools
    - libasound2-dev
    - libglib2.0-dev
    - libpulse-dev
    - libtool
    - make

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
