/*
 * Copyright (C) 2014 Michal Ratajsky <michal.ratajsky@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the licence, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#ifndef CAFEMIXER_ENUMS_H
#define CAFEMIXER_ENUMS_H

/*
 * GTypes are not generated by glib-mkenums, see:
 * https://bugzilla.gnome.org/show_bug.cgi?id=621942
 */

/**
 * CafeMixerState:
 * @CAFE_MIXER_STATE_IDLE:
 *     Not connected.
 * @CAFE_MIXER_STATE_CONNECTING:
 *     Connection is in progress.
 * @CAFE_MIXER_STATE_READY:
 *     Connected.
 * @CAFE_MIXER_STATE_FAILED:
 *     Connection has failed.
 * @CAFE_MIXER_STATE_UNKNOWN:
 *     Unknown state. This state is used as an error indicator.
 *
 * State of a connection to a sound system.
 */
typedef enum {
    CAFE_MIXER_STATE_IDLE,
    CAFE_MIXER_STATE_CONNECTING,
    CAFE_MIXER_STATE_READY,
    CAFE_MIXER_STATE_FAILED,
    CAFE_MIXER_STATE_UNKNOWN
} CafeMixerState;

/**
 * CafeMixerBackendType:
 * @CAFE_MIXER_BACKEND_UNKNOWN:
 *     Unknown or undefined sound system backend type.
 * @CAFE_MIXER_BACKEND_PULSEAUDIO:
 *     PulseAudio sound system backend. It has the highest priority and
 *     will be the first one to try when you call cafe_mixer_context_open(),
 *     unless you select a specific sound system to connect to.
 * @CAFE_MIXER_BACKEND_ALSA:
 *     The Advanced Linux Sound Architecture sound system.
 * @CAFE_MIXER_BACKEND_OSS:
 *     The Open Sound System.
 * @CAFE_MIXER_BACKEND_NULL:
 *     Fallback backend which never fails to initialize, but provides no
 *     functionality. This backend has the lowest priority and will be used
 *     if you do not select a specific backend and it isn't possible to use
 *     any of the other backends.
 *
 * Constants identifying a sound system backend.
 */
typedef enum {
    CAFE_MIXER_BACKEND_UNKNOWN,
    CAFE_MIXER_BACKEND_PULSEAUDIO,
    CAFE_MIXER_BACKEND_ALSA,
    CAFE_MIXER_BACKEND_OSS,
    CAFE_MIXER_BACKEND_NULL
} CafeMixerBackendType;

/**
 * CafeMixerBackendFlags:
 * @CAFE_MIXER_BACKEND_NO_FLAGS:
 *     No flags.
 * @CAFE_MIXER_BACKEND_HAS_APPLICATION_CONTROLS:
 *     The sound system backend includes support for application stream controls,
 *     allowing per-application volume control.
 * @CAFE_MIXER_BACKEND_HAS_STORED_CONTROLS:
 *     The sound system backend includes support for stored controls. See the
 *     #CafeMixerStoredControl description for more information.
 *     The presence of this flag does not guarantee that this feature is enabled
 *     in the sound system's configuration.
 * @CAFE_MIXER_BACKEND_CAN_SET_DEFAULT_INPUT_STREAM:
 *     The sound system backend is able to change the current default input stream
 *     using the cafe_mixer_context_set_default_input_stream() function.
 * @CAFE_MIXER_BACKEND_CAN_SET_DEFAULT_OUTPUT_STREAM:
 *     The sound system backend is able to change the current default output stream
 *     using the cafe_mixer_context_set_default_output_stream() function.
 *
 * Flags describing capabilities of a sound system.
 */
typedef enum { /*< flags >*/
    CAFE_MIXER_BACKEND_NO_FLAGS                      = 0,
    CAFE_MIXER_BACKEND_HAS_APPLICATION_CONTROLS      = 1 << 0,
    CAFE_MIXER_BACKEND_HAS_STORED_CONTROLS           = 1 << 1,
    CAFE_MIXER_BACKEND_CAN_SET_DEFAULT_INPUT_STREAM  = 1 << 2,
    CAFE_MIXER_BACKEND_CAN_SET_DEFAULT_OUTPUT_STREAM = 1 << 3
} CafeMixerBackendFlags;

/**
 * CafeMixerDirection:
 * @CAFE_MIXER_DIRECTION_UNKNOWN:
 *     Unknown direction.
 * @CAFE_MIXER_DIRECTION_INPUT:
 *     Input direction (recording).
 * @CAFE_MIXER_DIRECTION_OUTPUT:
 *     Output direction (playback).
 *
 * Sound stream direction.
 */
typedef enum {
    CAFE_MIXER_DIRECTION_UNKNOWN,
    CAFE_MIXER_DIRECTION_INPUT,
    CAFE_MIXER_DIRECTION_OUTPUT,
} CafeMixerDirection;

/**
 * CafeMixerStreamControlFlags:
 * @CAFE_MIXER_STREAM_CONTROL_NO_FLAGS:
 *     No flags.
 * @CAFE_MIXER_STREAM_CONTROL_MUTE_READABLE:
 *     The stream control includes a mute toggle and allows reading the mute state.
 * @CAFE_MIXER_STREAM_CONTROL_MUTE_WRITABLE:
 *     The stream control includes a mute toggle and allows changing the mute state.
 * @CAFE_MIXER_STREAM_CONTROL_VOLUME_READABLE:
 *     The stream control includes a volume control and allows reading the volume.
 * @CAFE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE:
 *     The stream control includes a volume control and allows changing the volume.
 * @CAFE_MIXER_STREAM_CONTROL_CAN_BALANCE:
 *     The stream control includes the necessary channel positions to allow left/right
 *     volume balancing.
 * @CAFE_MIXER_STREAM_CONTROL_CAN_FADE:
 *     The stream control includes the necessary channel positions to allow front/back
 *     volume fading.
 * @CAFE_MIXER_STREAM_CONTROL_MOVABLE:
 *     It is possible to move the stream control to a different stream using the
 *     cafe_mixer_stream_control_set_stream() function. See the function description
 *     for details.
 * @CAFE_MIXER_STREAM_CONTROL_HAS_DECIBEL:
 *     The stream controls supports decibel values and it is possible to successfully
 *     use the functions which operate on decibel values.
 * @CAFE_MIXER_STREAM_CONTROL_HAS_MONITOR:
 *     The stream control supports peak level monitoring.
 * @CAFE_MIXER_STREAM_CONTROL_STORED:
 *     The stream control is a #CafeMixerStoredControl.
 *
 * Flags describing capabilities and properties of a stream control.
 */
typedef enum {
    CAFE_MIXER_STREAM_CONTROL_NO_FLAGS        = 0,
    CAFE_MIXER_STREAM_CONTROL_MUTE_READABLE   = 1 << 0,
    CAFE_MIXER_STREAM_CONTROL_MUTE_WRITABLE   = 1 << 1,
    CAFE_MIXER_STREAM_CONTROL_VOLUME_READABLE = 1 << 2,
    CAFE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE = 1 << 3,
    CAFE_MIXER_STREAM_CONTROL_CAN_BALANCE     = 1 << 4,
    CAFE_MIXER_STREAM_CONTROL_CAN_FADE        = 1 << 5,
    CAFE_MIXER_STREAM_CONTROL_MOVABLE         = 1 << 6,
    CAFE_MIXER_STREAM_CONTROL_HAS_DECIBEL     = 1 << 7,
    CAFE_MIXER_STREAM_CONTROL_HAS_MONITOR     = 1 << 8,
    CAFE_MIXER_STREAM_CONTROL_STORED          = 1 << 9
} CafeMixerStreamControlFlags;

/**
 * CafeMixerStreamControlRole:
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_UNKNOWN:
 *     Unknown role.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_MASTER:
 *     Master volume control.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_APPLICATION:
 *     Application volume control.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_PCM:
 *     PCM volume control.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_SPEAKER:
 *     Speaker volume control.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_MICROPHONE:
 *     Microphone volume control.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_PORT:
 *     Volume control for a connector of a sound device.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_BOOST:
 *     Boost control (for example a microphone boost or bass boost).
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_BASS:
 *     Bass control.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_TREBLE:
 *     Treble control.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_CD:
 *     CD input volume control.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_VIDEO:
 *     Video volume control.
 * @CAFE_MIXER_STREAM_CONTROL_ROLE_MUSIC:
 *     Music volume control.
 */
typedef enum {
    CAFE_MIXER_STREAM_CONTROL_ROLE_UNKNOWN,
    CAFE_MIXER_STREAM_CONTROL_ROLE_MASTER,
    CAFE_MIXER_STREAM_CONTROL_ROLE_APPLICATION,
    CAFE_MIXER_STREAM_CONTROL_ROLE_PCM,
    CAFE_MIXER_STREAM_CONTROL_ROLE_SPEAKER,
    CAFE_MIXER_STREAM_CONTROL_ROLE_MICROPHONE,
    CAFE_MIXER_STREAM_CONTROL_ROLE_PORT,
    CAFE_MIXER_STREAM_CONTROL_ROLE_BOOST,
    CAFE_MIXER_STREAM_CONTROL_ROLE_BASS,
    CAFE_MIXER_STREAM_CONTROL_ROLE_TREBLE,
    CAFE_MIXER_STREAM_CONTROL_ROLE_CD,
    CAFE_MIXER_STREAM_CONTROL_ROLE_VIDEO,
    CAFE_MIXER_STREAM_CONTROL_ROLE_MUSIC
} CafeMixerStreamControlRole;

/**
 * CafeMixerStreamControlMediaRole:
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_UNKNOWN:
 *     Unknown media role.
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_VIDEO:
 *     Video role.
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_MUSIC:
 *     Music role.
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_GAME:
 *     Game role.
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_EVENT:
 *     Event sounds.
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_PHONE:
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_ANIMATION:
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_PRODUCTION:
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_A11Y:
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_TEST:
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_ABSTRACT:
 * @CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_FILTER:
 *
 * Constants describing a media role of a control. These constants are mapped
 * to PulseAudio media role property and therefore are only available when using
 * the PulseAudio sound system.
 *
 * Media roles are commonly set by applications to indicate what kind of sound
 * input/output they provide and may be the defining property of stored controls
 * (for example an event role stored control can be used to provide a volume
 * slider for event sounds).
 *
 * See the PulseAudio documentation for more detailed information about media
 * roles.
 */
typedef enum {
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_UNKNOWN,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_VIDEO,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_MUSIC,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_GAME,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_EVENT,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_PHONE,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_ANIMATION,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_PRODUCTION,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_A11Y,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_TEST,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_ABSTRACT,
    CAFE_MIXER_STREAM_CONTROL_MEDIA_ROLE_FILTER
} CafeMixerStreamControlMediaRole;

/**
 * CafeMixerDeviceSwitchRole:
 * @CAFE_MIXER_DEVICE_SWITCH_ROLE_UNKNOWN:
 *     Unknown device switch role.
 * @CAFE_MIXER_DEVICE_SWITCH_ROLE_PROFILE:
 *     The switch changes the active sound device profile.
 */
typedef enum {
    CAFE_MIXER_DEVICE_SWITCH_ROLE_UNKNOWN,
    CAFE_MIXER_DEVICE_SWITCH_ROLE_PROFILE,
} CafeMixerDeviceSwitchRole;

/**
 * CafeMixerStreamSwitchRole:
 * @CAFE_MIXER_STREAM_SWITCH_ROLE_UNKNOWN:
 *     Unknown stream switch role.
 * @CAFE_MIXER_STREAM_SWITCH_ROLE_PORT:
 *     The switch changes the active port.
 * @CAFE_MIXER_STREAM_SWITCH_ROLE_BOOST:
 *     The switch changes the boost value.
 */
typedef enum {
    CAFE_MIXER_STREAM_SWITCH_ROLE_UNKNOWN,
    CAFE_MIXER_STREAM_SWITCH_ROLE_PORT,
    CAFE_MIXER_STREAM_SWITCH_ROLE_BOOST
} CafeMixerStreamSwitchRole;

/**
 * CafeMixerStreamSwitchFlags:
 * @CAFE_MIXER_STREAM_SWITCH_NO_FLAGS:
 *     No flags.
 * @CAFE_MIXER_STREAM_SWITCH_TOGGLE:
 *     The switch is a #CafeMixerStreamToggle.
 */
typedef enum { /*< flags >*/
    CAFE_MIXER_STREAM_SWITCH_NO_FLAGS = 0,
    CAFE_MIXER_STREAM_SWITCH_TOGGLE   = 1 << 0,
} CafeMixerStreamSwitchFlags;

/**
 * CafeMixerChannelPosition:
 * @CAFE_MIXER_CHANNEL_UNKNOWN:
 *     Unknown channel position.
 * @CAFE_MIXER_CHANNEL_MONO:
 *     Mono channel. Only used for single-channel controls.
 * @CAFE_MIXER_CHANNEL_FRONT_LEFT:
 *     Front left channel.
 * @CAFE_MIXER_CHANNEL_FRONT_RIGHT:
 *     Front right channel.
 * @CAFE_MIXER_CHANNEL_FRONT_CENTER:
 *     Front center channel.
 * @CAFE_MIXER_CHANNEL_LFE:
 *     Low-frequency effects channel (subwoofer).
 * @CAFE_MIXER_CHANNEL_BACK_LEFT:
 *     Back (rear) left channel.
 * @CAFE_MIXER_CHANNEL_BACK_RIGHT:
 *     Back (rear) right channel.
 * @CAFE_MIXER_CHANNEL_BACK_CENTER:
 *     Back (rear) center channel.
 * @CAFE_MIXER_CHANNEL_FRONT_LEFT_CENTER:
 *     Front left of center channel.
 * @CAFE_MIXER_CHANNEL_FRONT_RIGHT_CENTER:
 *     Front right of center channel.
 * @CAFE_MIXER_CHANNEL_SIDE_LEFT:
 *     Side left channel.
 * @CAFE_MIXER_CHANNEL_SIDE_RIGHT:
 *     Side right channel.
 * @CAFE_MIXER_CHANNEL_TOP_FRONT_LEFT:
 *     Top front left channel.
 * @CAFE_MIXER_CHANNEL_TOP_FRONT_RIGHT:
 *     Top front right channel.
 * @CAFE_MIXER_CHANNEL_TOP_FRONT_CENTER:
 *     Top front center channel.
 * @CAFE_MIXER_CHANNEL_TOP_CENTER:
 *     Top center channel.
 * @CAFE_MIXER_CHANNEL_TOP_BACK_LEFT:
 *     Top back (rear) left channel.
 * @CAFE_MIXER_CHANNEL_TOP_BACK_RIGHT:
 *     Top back (rear) right channel.
 * @CAFE_MIXER_CHANNEL_TOP_BACK_CENTER:
 *     Top back (rear) center channel.
 */
typedef enum {
    CAFE_MIXER_CHANNEL_UNKNOWN = 0,
    CAFE_MIXER_CHANNEL_MONO,
    CAFE_MIXER_CHANNEL_FRONT_LEFT,
    CAFE_MIXER_CHANNEL_FRONT_RIGHT,
    CAFE_MIXER_CHANNEL_FRONT_CENTER,
    CAFE_MIXER_CHANNEL_LFE,
    CAFE_MIXER_CHANNEL_BACK_LEFT,
    CAFE_MIXER_CHANNEL_BACK_RIGHT,
    CAFE_MIXER_CHANNEL_BACK_CENTER,
    CAFE_MIXER_CHANNEL_FRONT_LEFT_CENTER,
    CAFE_MIXER_CHANNEL_FRONT_RIGHT_CENTER,
    CAFE_MIXER_CHANNEL_SIDE_LEFT,
    CAFE_MIXER_CHANNEL_SIDE_RIGHT,
    CAFE_MIXER_CHANNEL_TOP_FRONT_LEFT,
    CAFE_MIXER_CHANNEL_TOP_FRONT_RIGHT,
    CAFE_MIXER_CHANNEL_TOP_FRONT_CENTER,
    CAFE_MIXER_CHANNEL_TOP_CENTER,
    CAFE_MIXER_CHANNEL_TOP_BACK_LEFT,
    CAFE_MIXER_CHANNEL_TOP_BACK_RIGHT,
    CAFE_MIXER_CHANNEL_TOP_BACK_CENTER,
    /*< private >*/
    CAFE_MIXER_CHANNEL_MAX
} CafeMixerChannelPosition;

#endif /* CAFEMIXER_ENUMS_H */
